package com.pyt.handbook.constant;

public enum GenericResponseStatus {
	SUCCESS, INVALID_PASSWORD, INVALID_EMAIL, USER_UNAVAILABLE, EXCEPTION,
	FAILURE, NOT_FOUND, BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, PLATO_FAILURE, MOBILE_EXISTS, EMAIL_EXISTS;
}
